L "echo 'usr/share/libkkc/rules/*' > libkkc-common.install"
L "echo 'usr/include/*'            > libkkc-dev.install"
L "echo 'usr/lib/*/lib*.so'        >>libkkc-dev.install"
L "echo 'usr/lib/*/pkgconfig/*'    >>libkkc-dev.install"
L "echo 'usr/share/vala/vapi/*'    >>libkkc-dev.install"
L "echo 'usr/bin/kkc'              > libkkc-utils.install"
L "echo 'usr/share/locale/'        >>libkkc-utils.install"
L "echo 'usr/lib/*/lib*.so.*'      >>libkkc2.install"
L "echo 'README'                   > libkkc-utils.docs"
L "echo 'debian/kkc.1'             > libkkc-utils.manpages"

